// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK-NsNJMAq_-iO_zE4fOFZVM4QJRPjPGE',
    appId: '1:274397796619:web:1f4c69749f56f5bf462a0e',
    messagingSenderId: '274397796619',
    projectId: 'quraan-app-71b48',
    authDomain: 'quraan-app-71b48.firebaseapp.com',
    storageBucket: 'quraan-app-71b48.appspot.com',
    measurementId: 'G-BNB1F3W906',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx60ZOF6Cs4bZE5rvo6TilPTL9Bi0-87I',
    appId: '1:274397796619:android:26732086a882f3e2462a0e',
    messagingSenderId: '274397796619',
    projectId: 'quraan-app-71b48',
    storageBucket: 'quraan-app-71b48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKBNXm1RJs4fO_VziSU_Mf0gj7ppatYKk',
    appId: '1:274397796619:ios:3b5cb7ab04821f67462a0e',
    messagingSenderId: '274397796619',
    projectId: 'quraan-app-71b48',
    storageBucket: 'quraan-app-71b48.appspot.com',
    iosClientId: '274397796619-9a6l5io5h376473667u26fquq3d7muig.apps.googleusercontent.com',
    iosBundleId: 'com.example.quraanAppTest',
  );
}
